name: GitHub Pages

on:
  push:
    branches:
      - master
      - develop
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: rename
        env:
          BRANCH_NAME: ${{github.head_ref}}
        run: mv ./original/source.html ./docs/${BRANCH_NAME}.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          keep_files: true
