name: GitHub Pages

on:
  push:
    branches:
      - master
      - develop
jobs:
  deploy:
    runs-on: ubuntu-20.04
    env:
      PUBLISH_DIR: /tmp/publish
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set branch name
        id: set_branch_name
        run: echo ::set-output name=branch_name::${GITHUB_REF#refs/*/}
      - name: rename
        run: mkdir -p ${{ env.PUBLISH_DIR }} && cp ./original/source.html ${_}/${{ steps.set_branch_name.outputs.branch_name }}.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.PUBLISH_DIR }}
          keep_files: true
